### PR TITLE
Adding Google Analytics tracking user.

### PR DESCRIPTION
**Pull request by mozartdiniz**
This code will send a pageView request to Google Analytics every time that the users changes the hash of the URL.

I created seated up the Google Analytics with my Gmail account. Anyone who would like to track the website activity just sends me the @gmail.com email account, and I will add to this account.

### CODE REVIEW

**Review by mvdam — APPROVED** [review]

**Review by Bjeaurn — APPROVED** [review]
Looks nice! Clean.

I'd like access to Analytics; `bjorn.schijff`

**Comment by mvdam** [comment]
@mozartdiniz Nice job! Could you add my Google account to the Analytics property? `martin.van.dam.ordina@gmail.com`

**Comment by mozartdiniz** [comment]
@mvdam I just added you as Admin.

**Comment by MauritsR** [comment]
+1 maurits.ridder@gmail.com

**Comment by SRferrero** [comment]
samuel1btoc@gmail.com :P

**Comment by mozartdiniz** [comment]
@SRferrero, @Bjeaurn and @MauritsRidder I added you guys to Codestar Google Analytics account. If you don't receive any email from Google with the invitation, let me know.

**Comment by Bjeaurn** [comment]
:shipit:

**Pull request merged**
